# Site settings
title: HanziGuide
email: tech@yorickreum.de
description: >
  Hanzi Guide helps you learn to write Traditional and Simplified Chinese characters with proper stroke order.
  Study the characters with clear, step-by-step animations.
  Based on the hanzi-writer project (github.com/chanind/hanzi-writer)
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://hanzi.guide" # the base hostname & protocol for your site
github_username:  yorickreum

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-sitemap

exclude:
  - node_modules
  - cdn/*/src
  - cdn/*/demo
  - cdn/*/all.js
  - cdn/*/all.json
  - vendor
  - cdn/*/vendor