# Site settings
title: Hanzi Guide
email: tech@yorickreum.de
description: >
  Learn to write Traditional and Simplified Chinese characters with animated stroke order.
  Practice Mandarin and Cantonese with 9000+ characters.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.hanzi.guide" # the base hostname & protocol for your site
github_username:  yorickreum

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-sitemap

exclude:
  - node_modules
  - cdn/*/src
  - cdn/*/demo
  - cdn/*/all.js
  - cdn/*/all.json
  - vendor
  - cdn/*/vendor